language: java
jdk:
  - openjdk11

branches:
  only:
    - main

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy *
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/own-waiter.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY #Travis repo settings에 설정된 값
    bucket: deploy-waiter
    region: ap-northeast-2
    skip_cleanup: true
    acl : private
    local_dir: deploy
    wait-until-deployed: true
    on: main

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY #Travis repo settings에 설정된 값
    bucket: deploy-waiter
    key: own-waiter.zip
    bundle_type: zip
    application: own-waiter-deploy
    deployment_group: own-waiter-deploy-group
    region: ap-northeast-2
    wait-until-deployed: true
    on: main

notifications:
  email:
    recipients:
      - brightdev.bs@gmail.com


